global:
  version: VERSION
  css:
    base:
      css/gdc_foundation.css: {}
      css/style.css: {}
  js:
    js/gdc_foundation.js: { }
    js/foundation.min.js: {minified: true}
    js/foundation_init.js: {}
    js/motion-ui.min.js: {minified: true}
  dependencies:
    - core/drupal
    - core/jquery
    - core/once
