name: GDC Foundation Sub-theme
description: "Custom sub-theme, inherits from the Foundation base theme read <a href=\"http://foundation.zurb.com/docs/index.php\">framework documentation</a>"
core: 8.x
core_version_requirement: ^8 || ^9 || ^10
type: theme
base theme: zurb_foundation

# Image appears on admin/appearance
# screenshot: images/screenshot.jpg

# Uncomment these lines and change "STARTER" to your theme name if you
# need to add custom CSS or JS
libraries:
 - gdc_foundation/global

# Regions are output in the page.html.twig

regions:
  meta_header: 'Meta header'
  header: Header
  help: Help
  page_top: 'Page top'
  page_bottom: 'Page bottom'
  highlighted: Highlighted
  content: Content
  sidebar_first: 'Left sidebar'
  sidebar_second: 'Right sidebar'
  footer_first: 'Footer first column'
  footer_second: 'Footer second column'
  footer_third: 'Footer third column'
  footer_fourth: 'Footer fourth column'
  footer_bottom: 'Footer bottom (full width)'
  left_off_canvas: 'Left off canvas'
  right_off_canvas: 'Right off canvas'
regions_hidden:
  page_top: 'Page top'
  page_bottom: 'Page bottom'

# Hidden regions
# regions_hidden[]: Page top
# regions_hidden[]: Page bottom

features:
  - slogan
  - favicon
  - comment_user_picture
  - node_user_picture
