<?php

/**
 * Implements hook_theme().
 */
function news_theme($existing, $type, $theme, $path) {
  return [
    'news_page' => [
      'template' => 'news-page',
      'variables' => [
        'nodes' => [],
        'subject_tags' => [],
        'temp_tags' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_page().
 */
function news_preprocess_page(array &$variables) {
  // Pass the terms to the template.
  if (\Drupal::routeMatch()->getRouteName() == 'news.view') {
    $variables['#attached']['library'][] = 'news/news-filter';
    $variables['#attached']['library'][] = 'core/jquery';
    $variables['#attached']['library'][] = 'news/news-styles';

  }
}

