global:
  version: VERSION
  css:
    theme:                       # <-- load late in cascade
      css/tbmenu_override.css: {}
      css/menu.css: {}
      css/block.css: {}
      css/gdc_foundation.css: {}
      css/gdc_app.css: {}
      css/style.css: {}
      css/lightbox.css: {}
  js:
    js/gdc_foundation.js: {}
    js/foundation_init.js: {}
    js/lightbox.min.js: {}
  dependencies:
    - core/drupal
    - core/jquery
    - core/once
    - zurb_foundation/global        # <-- Zurb first
    # Uncomment if your overrides depend on these:
    # - tb_megamenu/base
    # - extlink/drupal.extlink

gdc_font:
  version: VERSION
  css:
    theme:
      css/gdc_font.css: {}

testfont:
  version: VERSION
  css:
    theme:
      css/test.css: {}

publications:
  version: VERSION
  js:
    js/publications.js: {}
  css:
    theme:
      css/publications.css: {}
  dependencies:
    - gdc_foundation/global

publications_group:
  version: VERSION
  js:
    js/publications_group.js: {}
  css:
    theme:
      css/publications_group.css: {}
  dependencies:
    - gdc_foundation/global

news:
  version: VERSION
  js:
    js/news.js: {}
  css:
    theme:
      css/news.css: {}
  dependencies:
    - gdc_foundation/global

faqs:
  version: VERSION
  js:
    js/faqs.js: {}
  css:
    theme:
      css/faqs.css: {}
  dependencies:
    - gdc_foundation/global

community_tools:
  version: VERSION
  js:
    js/community_tools.js: {}
  css:
    theme:
      css/community_tools.css: {}
  dependencies:
    - gdc_foundation/global

biography:
  version: VERSION
  css:
    theme:
      css/biography.css: {}
  dependencies:
    - gdc_foundation/global

