<?php

/**
 * Implements hook_theme().
 */
function faqs_theme($existing, $type, $theme, $path) {
  return [
    'faqs_page' => [
      'template' => 'faqs-page',
      'variables' => [
        'nodes' => [],
        'subject_tags' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_page().
 */
function faqs_preprocess_page(array &$variables) {
  // Pass the terms to the template.
  if (\Drupal::routeMatch()->getRouteName() == 'faqs.view') {
    // Attach the JavaScript library to the FAQ page.
    $variables['#attached']['library'][] = 'faqs/faq-filter';
    $variables['#attached']['library'][] = 'core/jquery';
    $variables['#attached']['library'][] = 'faqs/faqs-styles';

  }
}

