name: Build and Push Docker Image
on:
  workflow_dispatch:
  push:
    branches:
      - gdc_2.0
permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  build-base-image:
    name: Build Base Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from the other repository
        uses: actions/checkout@v3
        with:
          repository: cbiit/drupal-docker
          ref: base
          path: ./drupal-docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the base image
        id: build-image
        run: |
          docker build --no-cache -t base ./drupal-docker
          docker save base > base-image.tar

      - name: Upload base image
        uses: actions/upload-artifact@v4
        with:
          name: base-image
          path: base-image.tar

  build-final-image:
    needs: build-base-image
    name: Build Final Image
    runs-on: ubuntu-latest
    steps:
      - name: Download base image
        uses: actions/download-artifact@v4
        with:
          name: base-image

      - name: Load base image
        run: |
          docker load < base-image.tar

      - name: Checkout code from this repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::543036708785:role/power-user-cicd-role
          role-session-name: GitHubActions

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2                  

      - name: Build and push the drupal image
        id: build-image
        env:
          ECR_REGISTRY: 543036708785.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: drupal
          IMAGE_TAG: latest
          docker_username: ${{ steps.login-ecr.outputs.docker_username_543036708785.dkr.ecr.us-east-1.amazonaws.com }}          
        run: |
          # Build, tag, and push image to Amazon ECR
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY
          docker build --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./docker
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

  start-new-container:
    needs: build-final-image
    runs-on: ubuntu-latest
    name: Start New Container    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::543036708785:role/power-user-cicd-role
          role-session-name: GitHubActions        
      - name: Get ECS Service Name
        id: get-service-name
        run: |
          SERVICE_ARN=$(aws ecs list-services --cluster Dev --query "serviceArns[0]" --output text)
          SERVICE_NAME=$(basename $SERVICE_ARN)
          echo "Service name: $SERVICE_NAME"
          echo "::set-output name=service_name::$SERVICE_NAME"          
      - name: Deploy to ECS
        env:
          AWS_REGION: us-east-1
          CLUSTER_NAME: Dev  # Replace with your cluster name
          SERVICE_NAME: ${{ steps.get-service-name.outputs.service_name }}    # Replace with your service name
          CONTAINER_NAME: drupal  # Replace with your container name
          IMAGE_URI: 543036708785.dkr.ecr.us-east-1.amazonaws.com/drupal:latest
        run: |
          # Update the ECS service to use the new image
          aws ecs update-service \
            --cluster $CLUSTER_NAME \
            --service $SERVICE_NAME \
            --force-new-deployment 

          # Optionally, you can register a new task definition if needed
          # aws ecs register-task-definition --cli-input-json file://task-definition.json

          
